name: "E2E tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.1
      with:
        go-version: 1.18
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
    - name: "Run E2E tests"
      run: make e2e-test INTEGRATION_OUTPUT_JUNIT="true"
    - name: "List namespaces"
      run: kubectl get namespace
