name: "Lint code"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.1
      with:
        go-version: 1.18
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - name: "Lint the code"
      run: make lint
    - name: "Verify generate"
      run: ./hack/verify-generate.sh
    - name: "Verify go clean"
      run: ./hack/verify-go-clean.sh
